name: Python Unit Test

on: [push]

jobs:
  place-holder:
    name: Python Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build
      run: python3 -m pip install build
    - name: Build motor_platform package
      run: python3 -m build src/motor_platform
    - name: Install motor_platform package
      run: python3 -m pip install src/motor_platform/
    - name: Run unittest
      run: ./python_unit_test.sh
